spring.application.name=centroSportivo

spring.datasource.url=jdbc:mysql://localhost:3306/sportivo
spring.datasource.username=root
spring.datasource.password=password1992
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# 3. Protocollo di sicurezza
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

server.port=8080
jwt.secret-key=423322-1-133-586444-2231566-01233-33333-123-099-2026
jwt.expiration=3600000

logging.level.org.springframework.web=DEBUG